version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: isucon13-myql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: isupipe-test
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
      TZ: 'Asia/Tokyo'
    volumes:
      - ../sql/initdb.d/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
